[package]
name = "experiment_receipts"
version = "0.2.0"
description = "Committed experiment receipt program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "experiment_receipts"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
idl-build = ["anchor-lang/idl-build"]
default = []

[dependencies]
anchor-lang = { version = "1.0.2" }
